apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifestore
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lifestore
  template:
    metadata:
      labels:
        app: lifestore
    spec:
      containers:
      - name: lifestore
        image: dgopsdrew/store-front:v1
        envFrom:
        - secretRef:
            name: env-vars        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifestore-db
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifestore-db
  template:
    metadata:
      labels:
        app: lifestore-db
    spec:
      containers:
      - name: lifestore-db
        image: dgopsdrew/store-db:v1
        envFrom:
        - secretRef:
            name: env-vars
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: lifestore
    name: lifestore-svc
    namespace: development
spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
    selector:
        app: lifestore
    type: LoadBalancer

