apiVersion: v1
kind: Namespace
metadata:
  name: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }} #If enabled is true we provide a custom namespac😀
  labels:
    name: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name }}-lifestore
  namespace: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name }}-lifestore
  template:
    metadata:
      labels:
        app: {{.Release.Name }}-lifestore
    spec:
      containers:
      - name: {{.Release.Name}}-lifestore-front
        image: dgopsdrew/store-front:v1
        envFrom:
        - secretRef:
            name: {{ .Release.Name}}-db-secret
        - configMapRef:
            name: {{.Release.Name}}-config    
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-lifestore-db
  namespace: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-lifestore-db
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-lifestore-db
    spec:
      containers:
      - name: {{.Release.Name}}-lifestore-db
        image: dgopsdrew/store-db:v1
        volumeMounts:
          - name: {{.Release.Name}}-mysql-data
            mountPath: /var/lib/mysql
        envFrom:
        - secretRef:
            name: {{.Release.Name}}-db-secret
        env:
        - name: MYSQL_DATABASE
          value: store    
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
      volumes:
        - name: {{.Release.Name}}-mysql-data
          persistentVolumeClaim:
            claimName: {{.Release.Name}}-mysql-data-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-mysql-data-claim
  namespace: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
            
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{.Release.Name}}-lifestore
    name: {{.Release.Name}}-lifestore-svc
    namespace: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
    selector:
        app: {{.Release.Name}}-lifestore
    type: LoadBalancer
---    
apiVersion: v1
kind: Service
metadata:
    labels:
        app: {{.Release.Name}}-lifestore-db
    name: {{.Release.Name}}-lifestore-svc-db
    namespace: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
        app: {{.Release.Name}}-lifestore-db            