apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ if .Values.namespace.enabled }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Name }}{{ end }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ default .Values.secrets.MYSQL_ROOT_PASSWORD "password" | b64enc | quote }}
  MYSQL_USER: {{ default .Values.secrets.MYSQL_USER "store" | b64enc | quote }}
  MYSQL_PASSWORD: {{ default .Values.secrets.MYSQL_PASSWORD "password" | b64enc | quote }}
